### ISSUE TITLE
WEDEPLOY_REDIS_TYPE need to be set

### ISSUE THREAD

**Issue by motss** [wedeploy/demo-redis#1]
Can the `wedeploy/redis` be used by everyone? It needs a flag to be set. Please advise.

**Comment by cirocosta** [comment]
Hi @motss !

`wedeploy/redis` is internal only and it should not be used by the general public. Sorry if we gave such impression.

cc @jonnilundy

**Comment by motss** [comment]
I see. Thanks for the response.
